sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
    - git
    - wget
    - ruby
    - gcc
    - make
    - bison
    - g++
    - libboost-dev
    - libboost-program-options-dev
    - libboost-serialization-dev
    - libmysql++-dev
    - software-properties-common
    - python-software-properties
    - dnsutils
before_script:
  - sudo add-apt-repository -y ppa:maxmind/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y libmaxminddb0 libmaxminddb-dev mmdb-bin
  - wget -O - "http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz" | gunzip > /tmp/GeoLite2-City.mmdb
  - sudo bash build-scripts/travis-install-pdns.sh
  - echo "local-address=127.0.0.1" >> pdns-mruby.conf.sample
  - sudo cp pdns-mruby.conf.sample /etc/powerdns/pdns.conf
  - sudo sed -e '/mruby-filename=/ s@^.*$@mruby-filename=/etc/powerdns/pdns-backend.rb@' -i /etc/powerdns/pdns.conf
  - sudo cp examples/pdns-backend.rb /etc/powerdns/pdns-backend.rb
script:
  - bash ./build.sh
  - sudo cp src/libmrubybackend.so /usr/lib/x86_64-linux-gnu/pdns/libmrubybackend.so
  - sudo /usr/sbin/pdns_server --daemon 2>&1
  - pgrep pdns_server
  - dig +answer @127.0.0.1 example.jp. ANY
  - dig +answer @127.0.0.1 example.jp. TXT | grep -qF "Powerdns::Request::remote_addr=127.0.0.1"
  - dig +answer @127.0.0.1 com.example.jp. A | grep -qF "93.184.216.34"
  - pgrep pdns_server
