sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
    - git
    - wget
    - ruby
    - gcc
    - make
    - bison
    - g++
    - libboost-dev
    - libboost-program-options-dev
    - libboost-serialization-dev
    - libmysql++-dev
    - libgeoip-dev
    - dnsutils
    - lsof
before_script:
  - wget -O - "http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz" | gunzip > /tmp/GeoLiteCity.dat
  - sudo bash build-scripts/travis-install-pdns.sh
  - echo "local-address=127.0.0.1" >> pdns-mruby.conf.sample
  - sudo cp pdns-mruby.conf.sample /etc/powerdns/pdns.conf
  - sudo sed -e '/mruby-filename=/ s@^.*$@mruby-filename=/etc/powerdns/pdns-backend.rb@' -i /etc/powerdns/pdns.conf
  - sudo cp examples/pdns-backend.rb /etc/powerdns/pdns-backend.rb
  - sudo sed -e '/^\$db_path =/ s@".*"@"/tmp/GeoLiteCity.dat"@' -i /etc/powerdns/pdns-backend.rb
script:
  - bash ./build.sh
  - sudo cp src/libmrubybackend.so /usr/lib/x86_64-linux-gnu/pdns/libmrubybackend.so
  - sudo /usr/sbin/pdns_server --daemon 2>&1
  - pgrep pdns_server
  - dig +answer @127.0.0.1 example.jp. ANY
  - dig +answer @127.0.0.1 example.jp. TXT | grep -qF "Powerdns::Request::remote_addr=127.0.0.1"
  - pgrep pdns_server
  - sudo grep -F pdns /var/log/syslog
  - sudo lsof -n
