language: c
compiler:
  - gcc
#sudo: false
addons:
  apt:
    packages:
    - git
    - wget
    - ruby
    - gcc
    - rake
    - make
    - bison
    - g++
    - libboost-dev
    - libboost-program-options-dev
    - libboost-serialization-dev
    - libmysql++-dev
    - libgeoip-dev
    - dnsutils
#before_install:
#    - sudo apt-get -qq update
#install:
#    - sudo apt-get -qq install git wget ruby gcc rake make bison g++ libboost-dev libboost-program-options-dev libboost-serialization-dev libmysql++-dev libgeoip-dev
#before_script:
#  - cd ../
#  - git clone https://github.com/mruby/mruby.git
#  - cd mruby
#  - cp -fp ../mruby-namespace/.travis_build_config.rb build_config.rb
script:
  - bash ./build.sh
  - cp pdns-mruby.conf.sample /home/travis/opt/pdns/etc/pdns.conf
  - cp src/libmrubybackend.so /home/travis/opt/pdns/lib/pdns/
  - ( cd example && sudo /home/travis/opt/pdns/sbin/pdns_server --daemon )
  - pgrep -q pdns_server
  - dig +noall +answer @127.0.0.1 example.jp. ANY
